networks:
  external:
    external: false
  internal:
    internal: true
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file: 
      - .mysql.env
    networks:
      - internal
      - external
    ports:
      - "3306:3306"
    volumes: 
      - "./mysql:/var/lib/mysql"
    tty: true
    stdin_open: true
  server:
    depends_on:
        - db
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .mc.env
    networks:
      - internal
      - external
    ports: 
      - "25565:25565"
      - "8192:8192"
    restart: unless-stopped
    volumes:
      - "./server:/app/papermc"
    tty: true
    stdin_open: true
version: "3"
